In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('F:\Football_App\Data\FIFA 2018 Statistics.csv')
df.head()

Date          Team      Opponent  Goal Scored  Ball Possession %  \
0  14-06-2018        Russia  Saudi Arabia            5                 40   
1  14-06-2018  Saudi Arabia        Russia            0                 60   
2  15-06-2018         Egypt       Uruguay            0                 43   
3  15-06-2018       Uruguay         Egypt            1                 57   
4  15-06-2018       Morocco          Iran            0                 64   

   Attempts  On-Target  Off-Target  Blocked  Corners  ...  Yellow Card  \
0        13          7           3        3        6  ...            0   
1         6          0           3        3        2  ...            0   
2         8          3           3        2        0  ...            2   
3        14          4           6        4        5  ...            0   
4        13          3           6        4        5  ...            1   

   Yellow & Red  Red  Man of the Match  1st Goal        Round  PSO  \
0             0    0               Yes      12.0  Group Stage   No   
1             0    0                No       NaN  Group Stage   No   
2             0    0                No       NaN  Group Stage   No   
3             0    0               Yes      89.0  Group Stage   No   
4             0    0                No       NaN  Group Stage   No   

   Goals in PSO  Own goals  Own goal Time  
0             0        NaN            NaN  
1             0        NaN            NaN  
2             0        NaN            NaN  
3             0        NaN            NaN  
4             0        1.0           90.0  

[5 rows x 27 columns]

In [3]:
df.columns

Index(['Date', 'Team', 'Opponent', 'Goal Scored', 'Ball Possession %',
       'Attempts', 'On-Target', 'Off-Target', 'Blocked', 'Corners', 'Offsides',
       'Free Kicks', 'Saves', 'Pass Accuracy %', 'Passes',
       'Distance Covered (Kms)', 'Fouls Committed', 'Yellow Card',
       'Yellow & Red', 'Red', 'Man of the Match', '1st Goal', 'Round', 'PSO',
       'Goals in PSO', 'Own goals', 'Own goal Time'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Date                    128 non-null    object 
 1   Team                    128 non-null    object 
 2   Opponent                128 non-null    object 
 3   Goal Scored             128 non-null    int64  
 4   Ball Possession %       128 non-null    int64  
 5   Attempts                128 non-null    int64  
 6   On-Target               128 non-null    int64  
 7   Off-Target              128 non-null    int64  
 8   Blocked                 128 non-null    int64  
 9   Corners                 128 non-null    int64  
 10  Offsides                128 non-null    int64  
 11  Free Kicks              128 non-null    int64  
 12  Saves                   128 non-null    int64  
 13  Pass Accuracy %         128 non-null    int64  
 14  Passes                  128 non-null    in

In [5]:
df.describe().round(2)

Goal Scored  Ball Possession %  Attempts  On-Target  Off-Target  \
count       128.00             128.00    128.00     128.00      128.00   
mean          1.32              49.99     12.59       3.91        5.27   
std           1.16              10.44      5.25       2.23        2.41   
min           0.00              25.00      3.00       0.00        1.00   
25%           0.00              42.00      9.00       2.00        4.00   
50%           1.00              50.00     12.00       3.50        5.00   
75%           2.00              58.00     15.00       5.00        7.00   
max           6.00              75.00     26.00      12.00       11.00   

       Blocked  Corners  Offsides  Free Kicks   Saves  ...   Passes  \
count   128.00   128.00    128.00      128.00  128.00  ...   128.00   
mean      3.36     4.72      1.34       14.89    2.73  ...   462.65   
std       2.40     2.45      1.19        4.72    2.05  ...   151.19   
min       0.00     0.00      0.00        5.00    0.00  ...   189.00   
25%       1.75     3.00      0.00       11.00    1.00  ...   351.00   
50%       3.00     5.00      1.00       15.00    2.00  ...   462.00   
75%       4.00     6.00      2.00       18.00    4.00  ...   555.25   
max      10.00    11.00      5.00       26.00    9.00  ...  1137.00   

       Distance Covered (Kms)  Fouls Committed  Yellow Card  Yellow & Red  \
count                  128.00           128.00       128.00        128.00   
mean                   106.66            13.55         1.70          0.02   
std                     11.75             4.62         1.33          0.12   
min                     80.00             5.00         0.00          0.00   
25%                    101.00            10.00         1.00          0.00   
50%                    104.50            13.00         2.00          0.00   
75%                    109.00            16.00         2.00          0.00   
max                    148.00            25.00         6.00          1.00   

          Red  1st Goal  Goals in PSO  Own goals  Own goal Time  
count  128.00     94.00        128.00       12.0          12.00  
mean     0.02     39.46          0.20        1.0          45.83  
std      0.12     24.50          0.81        0.0          29.98  
min      0.00      1.00          0.00        1.0          12.00  
25%      0.00     18.25          0.00        1.0          21.75  
50%      0.00     39.00          0.00        1.0          35.00  
75%      0.00     54.75          0.00        1.0          75.75  
max      1.00     90.00          4.00        1.0          90.00  

[8 rows x 21 columns]

In [6]:
df.isnull().sum()

Date                        0
Team                        0
Opponent                    0
Goal Scored                 0
Ball Possession %           0
Attempts                    0
On-Target                   0
Off-Target                  0
Blocked                     0
Corners                     0
Offsides                    0
Free Kicks                  0
Saves                       0
Pass Accuracy %             0
Passes                      0
Distance Covered (Kms)      0
Fouls Committed             0
Yellow Card                 0
Yellow & Red                0
Red                         0
Man of the Match            0
1st Goal                   34
Round                       0
PSO                         0
Goals in PSO                0
Own goals                 116
Own goal Time             116
dtype: int64

In [7]:
df['1st Goal'].unique()

array([12., nan, 89., 90.,  4., 24., 58., 62., 19., 23., 59., 32., 56.,
       35., 20., 50., 65., 47., 11., 39.,  6., 37., 60., 54.,  7., 38.,
       34., 53., 49.,  5., 52., 18., 26., 48.,  8., 78., 40., 10., 45.,
       22., 14., 51., 76., 36., 31., 74., 33., 13., 41., 55.,  1., 69.,
       66., 57., 30., 68., 28.])

In [8]:
df['Own goals'].unique()

array([nan,  1.])

In [9]:
df['Own goal Time'].unique()

array([nan, 90., 81., 32., 37., 47., 23., 74., 33., 12., 13., 18.])

In [10]:
df['Own goals'] = df['Own goals'].fillna(0)

In [11]:
df['Own goals'].unique()

array([0., 1.])

In [12]:
df['Own goal Time'] = df['Own goal Time'].fillna(0)

In [13]:
df['Own goal Time'].unique()

array([ 0., 90., 81., 32., 37., 47., 23., 74., 33., 12., 13., 18.])

In [14]:
df['1st Goal'] = df['1st Goal'].fillna(0)

In [15]:
df['1st Goal'].unique()

array([12.,  0., 89., 90.,  4., 24., 58., 62., 19., 23., 59., 32., 56.,
       35., 20., 50., 65., 47., 11., 39.,  6., 37., 60., 54.,  7., 38.,
       34., 53., 49.,  5., 52., 18., 26., 48.,  8., 78., 40., 10., 45.,
       22., 14., 51., 76., 36., 31., 74., 33., 13., 41., 55.,  1., 69.,
       66., 57., 30., 68., 28.])

In [16]:
df.isnull().sum()

Date                      0
Team                      0
Opponent                  0
Goal Scored               0
Ball Possession %         0
Attempts                  0
On-Target                 0
Off-Target                0
Blocked                   0
Corners                   0
Offsides                  0
Free Kicks                0
Saves                     0
Pass Accuracy %           0
Passes                    0
Distance Covered (Kms)    0
Fouls Committed           0
Yellow Card               0
Yellow & Red              0
Red                       0
Man of the Match          0
1st Goal                  0
Round                     0
PSO                       0
Goals in PSO              0
Own goals                 0
Own goal Time             0
dtype: int64

In [17]:
df.columns

Index(['Date', 'Team', 'Opponent', 'Goal Scored', 'Ball Possession %',
       'Attempts', 'On-Target', 'Off-Target', 'Blocked', 'Corners', 'Offsides',
       'Free Kicks', 'Saves', 'Pass Accuracy %', 'Passes',
       'Distance Covered (Kms)', 'Fouls Committed', 'Yellow Card',
       'Yellow & Red', 'Red', 'Man of the Match', '1st Goal', 'Round', 'PSO',
       'Goals in PSO', 'Own goals', 'Own goal Time'],
      dtype='object')

In [18]:
df['Date'] = pd.to_datetime(df['Date'])

In [19]:
df.Date.unique()

<DatetimeArray>
['2018-06-14 00:00:00', '2018-06-15 00:00:00', '2018-06-16 00:00:00',
 '2018-06-17 00:00:00', '2018-06-18 00:00:00', '2018-06-19 00:00:00',
 '2018-06-20 00:00:00', '2018-06-21 00:00:00', '2018-06-22 00:00:00',
 '2018-06-23 00:00:00', '2018-06-24 00:00:00', '2018-06-25 00:00:00',
 '2018-06-26 00:00:00', '2018-06-27 00:00:00', '2018-06-28 00:00:00',
 '2018-06-30 00:00:00', '2018-07-01 00:00:00', '2018-07-02 00:00:00',
 '2018-07-03 00:00:00', '2018-07-06 00:00:00', '2018-07-07 00:00:00',
 '2018-07-10 00:00:00', '2018-07-11 00:00:00', '2018-07-14 00:00:00',
 '2018-07-15 00:00:00']
Length: 25, dtype: datetime64[ns]

In [20]:
df.columns

Index(['Date', 'Team', 'Opponent', 'Goal Scored', 'Ball Possession %',
       'Attempts', 'On-Target', 'Off-Target', 'Blocked', 'Corners', 'Offsides',
       'Free Kicks', 'Saves', 'Pass Accuracy %', 'Passes',
       'Distance Covered (Kms)', 'Fouls Committed', 'Yellow Card',
       'Yellow & Red', 'Red', 'Man of the Match', '1st Goal', 'Round', 'PSO',
       'Goals in PSO', 'Own goals', 'Own goal Time'],
      dtype='object')

In [29]:
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [31]:
df.drop(columns='Date',inplace = True)

In [21]:
col = ['Ball Possession %','Goal Scored','Free Kicks',
       'Pass Accuracy %','Yellow Card','Red',
       '1st Goal','Own goals','Own goal Time'
       ]

In [32]:
mainData = df.groupby(by = ['Month','Day','Team','Opponent'],as_index=False)[col].first()
mainData.head()

Month  Day          Team      Opponent  Ball Possession %  Goal Scored  \
0      6   14        Russia  Saudi Arabia                 40            5   
1      6   14  Saudi Arabia        Russia                 60            0   
2      6   15         Egypt       Uruguay                 43            0   
3      6   15          Iran       Morocco                 36            1   
4      6   15       Morocco          Iran                 64            0   

   Free Kicks  Pass Accuracy %  Yellow Card  Red  1st Goal  Own goals  \
0          11               78            0    0      12.0        0.0   
1          25               86            0    0       0.0        0.0   
2           7               78            2    0       0.0        0.0   
3          22               86            3    0      90.0        0.0   
4          14               86            1    0       0.0        1.0   

   Own goal Time  
0            0.0  
1            0.0  
2            0.0  
3            0.0  
4           90.0

In [23]:
mainData.to_csv('World Cup 2018.CSV')